#!/usr/bin/env python


def main():
	from argparse import ArgumentParser
	import ec2
	parser = ArgumentParser(description='Bootstrap Debian for the cloud.')
	parser.add_argument('--debug', action='store_true',
	                    help='Print debugging information')

	subparsers = parser.add_subparsers(title='providers', description='supported providers', dest='provider')
	ec2.init_subparser(subparsers)

	args = parser.parse_args()
	args.func(args)

if __name__ == '__main__' and __package__ is None:
	main()
