#!/bin/sh
# Kept for backward compatibility. OpenSSH Host Keys are generated
# by "ssh-generate-hostkeys.service" systemd unit or "ssh-generate-hostkeys"
# sysvinit script (#431).

set -eu

if [ -z "${1+x}" ] || [ -z "$1" ]; then
    PAR="start"
else
    PAR="$1"
fi

exec /etc/init.d/ssh-generate-hostkeys "$PAR"
